import api from "./api";
export const login = (email, password) => api.post("/auth/login", { email, password });
export const logout = () => api.post("/auth/logout");
export const fetchMe = () => api.get("/auth/me");
export const getOfficers = (params) => api.get("/officers", { params });
export const getOfficer = (id) => api.get(`/officers/${id}`);
export const createOfficer = (data) => api.post("/officers", data);
export const updateOfficer = (id, data) => api.put(`/officers/${id}`, data);
export const deleteOfficer = (id) => api.delete(`/officers/${id}`);
export const reassignOfficerSector = (id, sectorId) => api.put(`/officers/${id}/reassign-sector`, { sectorId, role: "PRIMARY_SI" });
export const getOfficerMemoTracker = (params) => api.get("/officers/memo-tracker", { params });
export const getOfficerMemos = (officerId) => api.get(`/officers/memo-tracker/${officerId}/memos`);
export const getViolations = (params) => api.get("/violations", { params });
export const exemptViolation = (id, reason) => api.post(`/violations/${id}/exempt`, { reason });
export const updateViolation = (id, data) => api.put(`/violations/${id}`, data);
export const deleteViolation = (id) => api.delete(`/violations/${id}`);
export const getCases = (params) => api.get("/cases", { params });
export const createCase = (data) => api.post("/cases", data);
export const updateCase = (id, data) => api.put(`/cases/${id}`, data);
export const deleteCase = (id) => api.delete(`/cases/${id}`);
export const getCaseStats = (type) => api.get(`/cases/stats/${type}`);
export const getActions = (params) => api.get("/actions", { params });
export const createAction = (data) => api.post("/actions", data);
export const updateAction = (id, data) => api.put(`/actions/${id}`, data);
export const deleteAction = (id) => api.delete(`/actions/${id}`);
export const getAppeals = (params) => api.get("/appeals", { params });
export const submitAppeal = (data) => api.post("/appeals", data);
export const updateAppeal = (id, data) => api.put(`/appeals/${id}`, data);
export const deleteAppeal = (id) => api.delete(`/appeals/${id}`);
export const getDSRs = (params) => api.get("/dsr", { params });
export const getDSR = (id) => api.get(`/dsr/${id}`);
export const getDSRDocument = (id) => api.get(`/dsr/${id}/document`);
export const getDSRCaseRows = (dsrId, caseId) => api.get(`/dsr/${dsrId}/case-rows/${caseId}`);
export const downloadDSRFile = (id) => api.get(`/dsr/${id}/download`, { responseType: "arraybuffer" });
export const getDSRDownloadUrl = (id) => `${api.defaults.baseURL}/dsr/${id}/download`;
export const reparseDSR = (id) => api.post(`/dsr/${id}/reparse`);
export const uploadDSR = (formData) => api.post("/dsr/upload", formData, { headers: { "Content-Type": "multipart/form-data" } });
export const getDSRStats = () => api.get("/dsr/stats/summary");
export const updateDSR = (id, data) => api.put(`/dsr/${id}`, data);
export const deleteDSR = (id) => api.delete(`/dsr/${id}`);
export const generateMemo = (data) => api.post("/memos/generate", data);
export const generateChargeMemo = (data) => api.post("/memos/generate-charge-memo", data);
export const getMemos = (params) => api.get("/memos", { params });
export const getMemoCounts = (params) => api.get("/memos/counts", { params });
export const getMemo = (id) => api.get(`/memos/${id}`);
export const updateMemo = (id, data) => api.put(`/memos/${id}`, data);
export const submitMemoForReview = (id) => api.put(`/memos/${id}/submit`);
export const assignMemoRecipient = (id, data) => api.put(`/memos/${id}/assign`, data);
export const approveMemo = (id) => api.put(`/memos/${id}/approve`);
export const holdMemo = (id, remarks) => api.put(`/memos/${id}/hold`, { remarks });
export const rejectMemo = (id, remarks) => api.put(`/memos/${id}/reject`, { remarks });
export const deleteMemo = (id) => api.delete(`/memos/${id}`);
export const complyMemo = (id, formData) => api.put(`/memos/${id}/comply`, formData, { headers: { "Content-Type": "multipart/form-data" } });
export const updateCompliance = (id, formData) => api.patch(`/memos/${id}/compliance`, formData, { headers: { "Content-Type": "multipart/form-data" } });
export const deleteComplianceDocument = (id) => api.delete(`/memos/${id}/compliance-document`);
export const downloadComplianceDocument = (id) => api.get(`/memos/${id}/compliance-document`, { responseType: "blob" });
export const getCaseOfficers = (psId, sector) => api.get(`/memos/case-officers/${psId}`, { params: { sector } });
export const getZones = () => api.get("/zones");
export const getHierarchy = () => api.get("/zones/hierarchy");
export const getDashboard = () => api.get("/reports/dashboard");
export const getBottomPerformers = () => api.get("/reports/bottom-performers");
export const getTopPerformers = () => api.get("/reports/top-performers");
export const getZoneComparison = () => api.get("/reports/zone-comparison");
export const getDashboardAnalytics = (params) => api.get("/reports/dashboard-analytics", { params });
export const getMappingHierarchy = () => api.get("/mapping/hierarchy");
export const getOfficerWarnings = () => api.get("/mapping/officer-warnings");
export const getGISData = () => api.get("/mapping/gis");
export const getPoliceStations = () => api.get("/zones/stations");
